apiVersion: v1
kind: Secret
metadata:
  name: myfilehash-s3-secret
data:
  key: #Base64エンコードしたアクセスキーID
  secret: #Base64エンコードしたシークレットアクセスキー
---
apiVersion: v1
kind: Secret
metadata:
  name: myfilehash-db-secret
data:
  user: #Base64エンコードしたmysqlユーザー
  pass: #Base64エンコードしたmysqlのパスワード
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: myfilehash-system-config
  namespace: default
data:
  common.dl-path: /dat/ #s3からダウンロードしたデータの保存場所（固定）
  s3.bucket: #S3のバケット名
  s3.rootdir: / #S3のディレクトリ
  db.host: #mysqlサーバー　ホスト名
  db.name: #データベース名
  method: MD5 #ハッシュ値計算の方法 MD5, SHA1, SHA224, SHA256, SHA384, SHA512
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: myfilehash-system
  labels:
    app: myfilehash-system
spec:
  replicas: 2
  selector:
    app: myfilehash-system
  template:
    metadata:
      name: myfilehash-system
      labels:
        app: myfilehash-system
    spec:
      containers:
      - name: file-hasher
        image: mmitti/file-hasher
        volumeMounts:
        - name: data
          mountPath: /dat
        env:
        - name: dl-path
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: common.dl-path
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: db.host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: myfilehash-db-secret
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: myfilehash-db-secret
              key: pass
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: db.name
        - name: METHOD
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: method

      - name: s3-fetch-tool
        image: mmitti/s3-fetch-tool
        volumeMounts:
        - name: data
          mountPath: /dat
        env:
        - name: dl-path
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: common.dl-path
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: s3.bucket
        - name: ROOT_DIR
          valueFrom:
            configMapKeyRef:
              name: myfilehash-system-config
              key: s3.rootdir
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: myfilehash-s3-secret
              key: key
        - name: ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: myfilehash-s3-secret
              key: secret
      volumes:
      - name: data
        emptyDir: {}
